package cloudoc.glucose;

//fbg count
rule "fbg count"
    ruleflow-group "statistic"
    dialect "mvel"
    // lock-on-active true

	when
	    $s : Statistic()
		$r : Record( acktype in (0, 2, 4) )
	then
		$s.fbgCount = $s.fbgCount + 1
end

//fbg normal count
rule "fbg normal count"
    extends "fbg count"
    ruleflow-group "statistic"
    dialect "mvel"
    // lock-on-active true
    
    when
        Record( level == 2 )
    then
		$s.fbgNormalCount = $s.fbgNormalCount + 1
end

//2 hpg count
rule "2 hpg count"
    ruleflow-group "statistic"
    dialect "mvel"
    // lock-on-active true
    
	when
	    $s : Statistic()
		$r : Record( acktype in (1, 3, 5) )
	then
		$s.twoHpgCount = $s.twoHpgCount + 1
end

//2 hpg normal count
rule "2 hpg normal count"
    extends "2 hpg count"
    ruleflow-group "statistic"
    dialect "mvel"
    // lock-on-active true
    
    when
        Record( level == 2 )
    then
		$s.twoHpgNormalCount = $s.twoHpgNormalCount + 1
end