package cloudoc.glucose;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Conclusion implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String title;
   private java.lang.String detail;

   private java.lang.String reason;

   public Conclusion()
   {
   }

   public java.lang.String getTitle()
   {
      return this.title;
   }

   public void setTitle(java.lang.String title)
   {
      this.title = title;
   }

   public java.lang.String getDetail()
   {
      return this.detail;
   }

   public void setDetail(java.lang.String detail)
   {
      this.detail = detail;
   }

   public java.lang.String getReason()
   {
      return this.reason;
   }

   public void setReason(java.lang.String reason)
   {
      this.reason = reason;
   }

   public Conclusion(java.lang.String title, java.lang.String detail,
         java.lang.String reason)
   {
      this.title = title;
      this.detail = detail;
      this.reason = reason;
   }

}