package cloudoc.glucose;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Conclusion implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Conclusion() {
    }

}