package cloudoc.glucose;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Patient implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Integer sex;
   private java.lang.Float weight;
   private java.lang.Float height;
   private java.lang.Boolean isDiabetes;
   private java.lang.Float hba1c;
   private java.lang.Boolean isHypertension;
   private java.lang.Integer sbp;
   private java.lang.Integer dbp;

   public Patient()
   {
   }

   public java.lang.Integer getSex()
   {
      return this.sex;
   }

   public void setSex(java.lang.Integer sex)
   {
      this.sex = sex;
   }

   public java.lang.Float getWeight()
   {
      return this.weight;
   }

   public void setWeight(java.lang.Float weight)
   {
      this.weight = weight;
   }

   public java.lang.Float getHeight()
   {
      return this.height;
   }

   public void setHeight(java.lang.Float height)
   {
      this.height = height;
   }

   public java.lang.Boolean getIsDiabetes()
   {
      return this.isDiabetes;
   }

   public void setIsDiabetes(java.lang.Boolean isDiabetes)
   {
      this.isDiabetes = isDiabetes;
   }

   public java.lang.Float getHba1c()
   {
      return this.hba1c;
   }

   public void setHba1c(java.lang.Float hba1c)
   {
      this.hba1c = hba1c;
   }

   public java.lang.Boolean getIsHypertension()
   {
      return this.isHypertension;
   }

   public void setIsHypertension(java.lang.Boolean isHypertension)
   {
      this.isHypertension = isHypertension;
   }

   public java.lang.Integer getSbp()
   {
      return this.sbp;
   }

   public void setSbp(java.lang.Integer sbp)
   {
      this.sbp = sbp;
   }

   public java.lang.Integer getDbp()
   {
      return this.dbp;
   }

   public void setDbp(java.lang.Integer dbp)
   {
      this.dbp = dbp;
   }

   public Patient(java.lang.Integer sex, java.lang.Float weight,
         java.lang.Float height, java.lang.Boolean isDiabetes,
         java.lang.Float hba1c, java.lang.Boolean isHypertension,
         java.lang.Integer sbp, java.lang.Integer dbp)
   {
      this.sex = sex;
      this.weight = weight;
      this.height = height;
      this.isDiabetes = isDiabetes;
      this.hba1c = hba1c;
      this.isHypertension = isHypertension;
      this.sbp = sbp;
      this.dbp = dbp;
   }

}