package cloudoc.glucose;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Record implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "\u8840\u7CD6\u6D4B\u91CF\u503C")
   private java.lang.Float value;
   @org.kie.api.definition.type.Label(value = "\u8840\u7CD6\u6D4B\u91CF\u70B9")
   private java.lang.Integer acktype;
   @org.kie.api.definition.type.Label(value = "\u8840\u7CD6\u8BC4\u4F30\u6C34\u5E73")
   private java.lang.Integer level;

   public Record()
   {
   }

   public java.lang.Float getValue()
   {
      return this.value;
   }

   public void setValue(java.lang.Float value)
   {
      this.value = value;
   }

   public java.lang.Integer getAcktype()
   {
      return this.acktype;
   }

   public void setAcktype(java.lang.Integer acktype)
   {
      this.acktype = acktype;
   }

   public java.lang.Integer getLevel()
   {
      return this.level;
   }

   public void setLevel(java.lang.Integer level)
   {
      this.level = level;
   }

   public Record(java.lang.Float value, java.lang.Integer acktype,
         java.lang.Integer level)
   {
      this.value = value;
      this.acktype = acktype;
      this.level = level;
   }

}