package cloudoc.glucose;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Statistic implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("????????")
   private java.lang.Integer fbgCount = 0;

   @org.kie.api.definition.type.Label("????????")
   private java.lang.Integer fbgNormalCount = 0;

   @org.kie.api.definition.type.Label("???????")
   private java.lang.Double fbgNormalPercentage = 0.0;

   @org.kie.api.definition.type.Label("??2????????")
   private java.lang.Integer twoHpgCount = 0;

   @org.kie.api.definition.type.Label("??2???????")
   private java.lang.Double twoHpgNormalPercentage = 0.0;

   @org.kie.api.definition.type.Label("??????<=3.9???")
   private java.lang.Integer hypoglycemiaCount = 0;

   @org.kie.api.definition.type.Label("??????>=16.7???")
   private java.lang.Integer hyperglycemiaCount = 0;

   @org.kie.api.definition.type.Label("?????????")
   private java.lang.Double averageFBG = 0.0;

   @org.kie.api.definition.type.Label("????????????")
   private java.lang.Double fbgStandardDeviation = 0.0;

   @org.kie.api.definition.type.Label("???????????")
   private java.lang.Double fbgVariance = 0.0;

   @org.kie.api.definition.type.Label("????????2???")
   private java.lang.Double averageTwoHpg = 0.0;

   @org.kie.api.definition.type.Label("????????2??????")
   private java.lang.Double twoHpgStandardDeviation = 0.0;

   @org.kie.api.definition.type.Label("????????2?????")
   private java.lang.Double twoHpgVariance = 0.0;

   @org.kie.api.definition.type.Label("??2????????")
   private java.lang.Integer twoHpgNormalCount = 0;

   private java.lang.Boolean fbgCountUpdated = false;

   private java.lang.Boolean fbgNormalCountUpdated = false;

   private java.lang.Boolean twoHpgCountUpdated = false;;

   private java.lang.Boolean twoHpgNormalCountUpdated = false;

   private java.lang.Boolean hypoglycemiaCountUpdated = false;

   private java.lang.Boolean hyperglycemiaCountUpdated = false;

   private java.lang.Boolean averageFBGUpdated = false;

   public Statistic()
   {
   }

   public java.lang.Integer getFbgCount()
   {
      return this.fbgCount;
   }

   public void setFbgCount(java.lang.Integer fbgCount)
   {
      this.fbgCount = fbgCount;
   }

   public java.lang.Integer getFbgNormalCount()
   {
      return this.fbgNormalCount;
   }

   public void setFbgNormalCount(java.lang.Integer fbgNormalCount)
   {
      this.fbgNormalCount = fbgNormalCount;
   }

   public java.lang.Double getFbgNormalPercentage()
   {
      return this.fbgNormalPercentage;
   }

   public void setFbgNormalPercentage(java.lang.Double fbgNormalPercentage)
   {
      this.fbgNormalPercentage = fbgNormalPercentage;
   }

   public java.lang.Integer getTwoHpgCount()
   {
      return this.twoHpgCount;
   }

   public void setTwoHpgCount(java.lang.Integer twoHpgCount)
   {
      this.twoHpgCount = twoHpgCount;
   }

   public java.lang.Double getTwoHpgNormalPercentage()
   {
      return this.twoHpgNormalPercentage;
   }

   public void setTwoHpgNormalPercentage(java.lang.Double twoHpgNormalPercentage)
   {
      this.twoHpgNormalPercentage = twoHpgNormalPercentage;
   }

   public java.lang.Integer getHypoglycemiaCount()
   {
      return this.hypoglycemiaCount;
   }

   public void setHypoglycemiaCount(java.lang.Integer hypoglycemiaCount)
   {
      this.hypoglycemiaCount = hypoglycemiaCount;
   }

   public java.lang.Integer getHyperglycemiaCount()
   {
      return this.hyperglycemiaCount;
   }

   public void setHyperglycemiaCount(java.lang.Integer hyperglycemiaCount)
   {
      this.hyperglycemiaCount = hyperglycemiaCount;
   }

   public java.lang.Double getAverageFBG()
   {
      return this.averageFBG;
   }

   public void setAverageFBG(java.lang.Double averageFBG)
   {
      this.averageFBG = averageFBG;
   }

   public java.lang.Double getFbgStandardDeviation()
   {
      return this.fbgStandardDeviation;
   }

   public void setFbgStandardDeviation(java.lang.Double fbgStandardDeviation)
   {
      this.fbgStandardDeviation = fbgStandardDeviation;
   }

   public java.lang.Double getFbgVariance()
   {
      return this.fbgVariance;
   }

   public void setFbgVariance(java.lang.Double fbgVariance)
   {
      this.fbgVariance = fbgVariance;
   }

   public java.lang.Double getAverageTwoHpg()
   {
      return this.averageTwoHpg;
   }

   public void setAverageTwoHpg(java.lang.Double averageTwoHpg)
   {
      this.averageTwoHpg = averageTwoHpg;
   }

   public java.lang.Double getTwoHpgStandardDeviation()
   {
      return this.twoHpgStandardDeviation;
   }

   public void setTwoHpgStandardDeviation(java.lang.Double twoHpgStandardDeviation)
   {
      this.twoHpgStandardDeviation = twoHpgStandardDeviation;
   }

   public java.lang.Double getTwoHpgVariance()
   {
      return this.twoHpgVariance;
   }

   public void setTwoHpgVariance(java.lang.Double twoHpgVariance)
   {
      this.twoHpgVariance = twoHpgVariance;
   }

   public java.lang.Integer getTwoHpgNormalCount()
   {
      return this.twoHpgNormalCount;
   }

   public void setTwoHpgNormalCount(java.lang.Integer twoHpgNormalCount)
   {
      this.twoHpgNormalCount = twoHpgNormalCount;
   }

   public java.lang.Boolean getFbgCountUpdated()
   {
      return this.fbgCountUpdated;
   }

   public void setFbgCountUpdated(java.lang.Boolean fbgCountUpdated)
   {
      this.fbgCountUpdated = fbgCountUpdated;
   }

   public java.lang.Boolean getFbgNormalCountUpdated()
   {
      return this.fbgNormalCountUpdated;
   }

   public void setFbgNormalCountUpdated(java.lang.Boolean fbgNormalCountUpdated)
   {
      this.fbgNormalCountUpdated = fbgNormalCountUpdated;
   }

   public java.lang.Boolean getTwoHpgCountUpdated()
   {
      return this.twoHpgCountUpdated;
   }

   public void setTwoHpgCountUpdated(java.lang.Boolean twoHpgCountUpdated)
   {
      this.twoHpgCountUpdated = twoHpgCountUpdated;
   }

   public java.lang.Boolean getTwoHpgNormalCountUpdated()
   {
      return this.twoHpgNormalCountUpdated;
   }

   public void setTwoHpgNormalCountUpdated(
         java.lang.Boolean twoHpgNormalCountUpdated)
   {
      this.twoHpgNormalCountUpdated = twoHpgNormalCountUpdated;
   }

   public java.lang.Boolean getHypoglycemiaCountUpdated()
   {
      return this.hypoglycemiaCountUpdated;
   }

   public void setHypoglycemiaCountUpdated(
         java.lang.Boolean hypoglycemiaCountUpdated)
   {
      this.hypoglycemiaCountUpdated = hypoglycemiaCountUpdated;
   }

   public java.lang.Boolean getHyperglycemiaCountUpdated()
   {
      return this.hyperglycemiaCountUpdated;
   }

   public void setHyperglycemiaCountUpdated(
         java.lang.Boolean hyperglycemiaCountUpdated)
   {
      this.hyperglycemiaCountUpdated = hyperglycemiaCountUpdated;
   }

   public java.lang.Boolean getAverageFBGUpdated()
   {
      return this.averageFBGUpdated;
   }

   public void setAverageFBGUpdated(java.lang.Boolean averageFBGUpdated)
   {
      this.averageFBGUpdated = averageFBGUpdated;
   }

   public Statistic(java.lang.Integer fbgCount, java.lang.Integer fbgNormalCount,
         java.lang.Double fbgNormalPercentage, java.lang.Integer twoHpgCount,
         java.lang.Double twoHpgNormalPercentage,
         java.lang.Integer hypoglycemiaCount,
         java.lang.Integer hyperglycemiaCount, java.lang.Double averageFBG,
         java.lang.Double fbgStandardDeviation, java.lang.Double fbgVariance,
         java.lang.Double averageTwoHpg,
         java.lang.Double twoHpgStandardDeviation,
         java.lang.Double twoHpgVariance, java.lang.Integer twoHpgNormalCount,
         java.lang.Boolean fbgCountUpdated,
         java.lang.Boolean fbgNormalCountUpdated,
         java.lang.Boolean twoHpgCountUpdated,
         java.lang.Boolean twoHpgNormalCountUpdated,
         java.lang.Boolean hypoglycemiaCountUpdated,
         java.lang.Boolean hyperglycemiaCountUpdated,
         java.lang.Boolean averageFBGUpdated)
   {
      this.fbgCount = fbgCount;
      this.fbgNormalCount = fbgNormalCount;
      this.fbgNormalPercentage = fbgNormalPercentage;
      this.twoHpgCount = twoHpgCount;
      this.twoHpgNormalPercentage = twoHpgNormalPercentage;
      this.hypoglycemiaCount = hypoglycemiaCount;
      this.hyperglycemiaCount = hyperglycemiaCount;
      this.averageFBG = averageFBG;
      this.fbgStandardDeviation = fbgStandardDeviation;
      this.fbgVariance = fbgVariance;
      this.averageTwoHpg = averageTwoHpg;
      this.twoHpgStandardDeviation = twoHpgStandardDeviation;
      this.twoHpgVariance = twoHpgVariance;
      this.twoHpgNormalCount = twoHpgNormalCount;
      this.fbgCountUpdated = fbgCountUpdated;
      this.fbgNormalCountUpdated = fbgNormalCountUpdated;
      this.twoHpgCountUpdated = twoHpgCountUpdated;
      this.twoHpgNormalCountUpdated = twoHpgNormalCountUpdated;
      this.hypoglycemiaCountUpdated = hypoglycemiaCountUpdated;
      this.hyperglycemiaCountUpdated = hyperglycemiaCountUpdated;
      this.averageFBGUpdated = averageFBGUpdated;
   }

}