package cloudoc.glucose;

//from row number: 1
rule "ali rule row 1"
	dialect "mvel"
	ruleflow-group "ali_determination"
	when
		$p : Patient( isInsulinUsed == true , insulinFrequency >= 3 , isOADUsed == false )
		$s : Statistic( fbgNormalPercentage >= 0.6, twoHpgNormalPercentage >= 0.6 )
	then
		Conclusion $c = new Conclusion();
		$c.setTitle( "1" );
		insert( $c );
end

rule "ali rule row 2"
	dialect "mvel"
	ruleflow-group "ali_determination"
	when
		$p : Patient( isInsulinUsed == true , insulinFrequency >= 3 , isOADUsed == false )
		$s : Statistic( fbgNormalPercentage >= 0.6, twoHpgNormalPercentage < 0.6 )
	then
		Conclusion $c = new Conclusion();
		$c.setTitle( "2" );
		insert( $c );
end

rule "ali rule row 3"
	dialect "mvel"
	ruleflow-group "ali_determination"
	when
		$p : Patient( isInsulinUsed == true , insulinFrequency >= 3 , isOADUsed == false )
		$s : Statistic( fbgNormalPercentage < 0.6, twoHpgNormalPercentage < 0.6 )
	then
		Conclusion $c = new Conclusion();
		$c.setTitle( "3" );
		insert( $c );
end

rule "ali rule row 4"
	dialect "mvel"
	ruleflow-group "ali_determination"
	when
		$p : Patient( isInsulinUsed == true , insulinFrequency >= 3 , isOADUsed == false )
		$s : Statistic( fbgNormalPercentage < 0.6, twoHpgNormalPercentage >= 0.6 )
	then
		Conclusion $c = new Conclusion();
		$c.setTitle( "4" );
		insert( $c );
end

rule "ali rule row 5"
	dialect "mvel"
	ruleflow-group "ali_determination"
	when
		$p : Patient( isInsulinUsed == true , insulinFrequency == 2 , isOADUsed == false )
		$s : Statistic( fbgNormalPercentage >= 0.6, twoHpgNormalPercentage >= 0.6 )
	then
		Conclusion $c = new Conclusion();
		$c.setTitle( "5" );
		insert( $c );
end

rule "ali rule row 6"
	dialect "mvel"
	ruleflow-group "ali_determination"
	when
		$p : Patient( isInsulinUsed == true , insulinFrequency == 2 , isOADUsed == false )
		$s : Statistic( fbgNormalPercentage >= 0.6, twoHpgNormalPercentage < 0.6 )
	then
		Conclusion $c = new Conclusion();
		$c.setTitle( "6" );
		insert( $c );
end

rule "ali rule row 7"
	dialect "mvel"
	ruleflow-group "ali_determination"
	when
		$p : Patient( isInsulinUsed == true , insulinFrequency == 2 , isOADUsed == false )
		$s : Statistic( fbgNormalPercentage < 0.6, twoHpgNormalPercentage < 0.6 )
	then
		Conclusion $c = new Conclusion();
		$c.setTitle( "7" );
		insert( $c );
end

rule "ali rule row 8"
	dialect "mvel"
	ruleflow-group "ali_determination"
	when
		$p : Patient( isInsulinUsed == true , insulinFrequency == 2 , isOADUsed == false )
		$s : Statistic( fbgNormalPercentage < 0.6, twoHpgNormalPercentage >= 0.6 )
	then
		Conclusion $c = new Conclusion();
		$c.setTitle( "8" );
		insert( $c );
end

rule "ali rule row 9"
	dialect "mvel"
	ruleflow-group "ali_determination"
	when
		$p : Patient( isInsulinUsed == true , insulinFrequency == 1 , isOADUsed == false )
		$s : Statistic( fbgNormalPercentage >= 0.6, twoHpgNormalPercentage >= 0.6 )
	then
		Conclusion $c = new Conclusion();
		$c.setTitle( "9" );
		insert( $c );
end

rule "ali rule row 10"
	dialect "mvel"
	ruleflow-group "ali_determination"
	when
		$p : Patient( isInsulinUsed == true , insulinFrequency == 1 , isOADUsed == false )
		$s : Statistic( fbgNormalPercentage >= 0.6, twoHpgNormalPercentage < 0.6 )
	then
		Conclusion $c = new Conclusion();
		$c.setTitle( "10" );
		insert( $c );
end

rule "ali rule row 11"
	dialect "mvel"
	ruleflow-group "ali_determination"
	when
		$p : Patient( isInsulinUsed == true , insulinFrequency == 1 , isOADUsed == false )
		$s : Statistic( fbgNormalPercentage < 0.6, twoHpgNormalPercentage < 0.6 )
	then
		Conclusion $c = new Conclusion();
		$c.setTitle( "11" );
		insert( $c );
end

rule "ali rule row 12"
	dialect "mvel"
	ruleflow-group "ali_determination"
	when
		$p : Patient( isInsulinUsed == true , insulinFrequency == 1 , isOADUsed == false )
		$s : Statistic( fbgNormalPercentage < 0.6, twoHpgNormalPercentage >= 0.6 )
	then
		Conclusion $c = new Conclusion();
		$c.setTitle( "12" );
		insert( $c );
end

rule "ali rule row 13"
	dialect "mvel"
	ruleflow-group "ali_determination"
	when
		$p : Patient( isInsulinUsed == false , isOADUsed == true )
		$s : Statistic( fbgNormalPercentage >= 0.6, twoHpgNormalPercentage >= 0.6 )
	then
		Conclusion $c = new Conclusion();
		$c.setTitle( "13" );
		insert( $c );
end

rule "ali rule row 14"
	dialect "mvel"
	ruleflow-group "ali_determination"
	when
		$p : Patient( isInsulinUsed == false , isOADUsed == true )
		$s : Statistic( fbgNormalPercentage >= 0.6, twoHpgNormalPercentage < 0.6 )
	then
		Conclusion $c = new Conclusion();
		$c.setTitle( "14" );
		insert( $c );
end

rule "ali rule row 15"
	dialect "mvel"
	ruleflow-group "ali_determination"
	when
		$p : Patient( isInsulinUsed == false , isOADUsed == true )
		$s : Statistic( fbgNormalPercentage < 0.6, twoHpgNormalPercentage < 0.6 )
	then
		Conclusion $c = new Conclusion();
		$c.setTitle( "15" );
		insert( $c );
end

rule "ali rule row 16"
	dialect "mvel"
	ruleflow-group "ali_determination"
	when
		$p : Patient( isInsulinUsed == false , isOADUsed == true )
		$s : Statistic( fbgNormalPercentage < 0.6, twoHpgNormalPercentage >= 0.6 )
	then
		Conclusion $c = new Conclusion();
		$c.setTitle( "16" );
		insert( $c );
end

rule "ali rule row 17"
	dialect "mvel"
	ruleflow-group "ali_determination"
	when
		$p : Patient( isInsulinUsed == true , isOADUsed == true )
		$s : Statistic( fbgNormalPercentage >= 0.6, twoHpgNormalPercentage >= 0.6 )
	then
		Conclusion $c = new Conclusion();
		$c.setTitle( "17" );
		insert( $c );
end

rule "ali rule row 18"
	dialect "mvel"
	ruleflow-group "ali_determination"
	when
		$p : Patient( isInsulinUsed == true , isOADUsed == true )
		$s : Statistic( fbgNormalPercentage >= 0.6, twoHpgNormalPercentage < 0.6 )
	then
		Conclusion $c = new Conclusion();
		$c.setTitle( "18" );
		insert( $c );
end

rule "ali rule row 19"
	dialect "mvel"
	ruleflow-group "ali_determination"
	when
		$p : Patient( isInsulinUsed == true , isOADUsed == true )
		$s : Statistic( fbgNormalPercentage < 0.6, twoHpgNormalPercentage < 0.6 )
	then
		Conclusion $c = new Conclusion();
		$c.setTitle( "19" );
		insert( $c );
end

rule "ali rule row 20"
	dialect "mvel"
	ruleflow-group "ali_determination"
	when
		$p : Patient( isInsulinUsed == true , isOADUsed == true )
		$s : Statistic( fbgNormalPercentage < 0.6, twoHpgNormalPercentage >= 0.6 )
	then
		Conclusion $c = new Conclusion();
		$c.setTitle( "20" );
		insert( $c );
end