package cloudoc.glucose;

//only diabetes
rule "only diabetes"
    ruleflow-group "determination"
    no-loop
    
    when
        $p : Patient( isDiabetes == true )
        $s : Statistic()
        not( exists( Record() ) )
    then
        Conclusion c = new Conclusion();
        c.setTitle("weekly report");
        insertLogical(c);
end

//record count <= 2
rule "record count <= 2"
    ruleflow-group "determination"

    when
        $p : Patient( isDiabetes == true )
        $s : Statistic( fbgCount + twoHpgCount <= 2 )
    then
        Conclusion c = new Conclusion();
        c.setTitle("\u8840\u7cd6\u76d1\u6d4b\u60c5\u51b5");
        insertLogical(c);
        Conclusion c2 = new Conclusion();
        c.setTitle("\u8bc4\u4f30\u548c\u76ee\u6807");
        insertLogical(c2);
end

rule "record count <= 2, and hypoglycemiaCount > 0"
    extends "record count <= 2"
    ruleflow-group "determination"

    when
        Statistic( hypoglycemiaCount > 0 )
    then
        Conclusion c = new Conclusion();
        c.setTitle("hypoglycemiaCount > 0");
        insertLogical(c);
end

rule "record count <= 2, and hypoglycemiaCount == 0"
    extends "record count <= 2"
    ruleflow-group "determination"

    when
        Statistic( hypoglycemiaCount == 0 )
    then
        Conclusion c = new Conclusion();
        c.setTitle("hypoglycemiaCount == 0");
        insertLogical(c);
end
