package cloudoc.glucose;

//only diabetes
// rule "only diabetes"
//     ruleflow-group "determination"
//     salience -10

//     when
//         Patient( isDiabetes == true )
//         not( Record() )
//     then
//         Conclusion c = new Conclusion();
//         c.setTitle("weekly report");
//         insert(c);
// end

//fbgCount + twoHpgCount <= 2
rule "fbgCount + twoHpgCount <= 2"
    ruleflow-group "determination"
    // salience 40
    no-loop true
    
    when
        Patient( isDiabetes == true )
        $s : Statistic( fbgCount + twoHpgCount <= 2 )
    then
        Conclusion c = new Conclusion();
        c.setTitle("\u8840\u7cd6\u76d1\u6d4b\u60c5\u51b5");
        // insert(c);
        Conclusion c2 = new Conclusion();
        c2.setTitle("\u8bc4\u4f30\u548c\u76ee\u6807");
        // insert(c2);
        modify($s) {
            addConclusion(c),
            addConclusion(c2);
        }
end

rule "fbgCount + twoHpgCount <= 2, and hypoglycemiaCount > 0"
    extends "fbgCount + twoHpgCount <= 2"
    ruleflow-group "determination"
    // salience 40
    lock-on-active true

    when
        Statistic( hypoglycemiaCount > 0 )
    then
        Conclusion c = new Conclusion();
        c.setTitle("hypoglycemiaCount > 0");
        // insert(c);
        modify($s) {
            addConclusion(c);
        }
end

rule "fbgCount + twoHpgCount <= 2, and hypoglycemiaCount == 0"
    extends "fbgCount + twoHpgCount <= 2"
    ruleflow-group "determination"
    // salience 40
    lock-on-active true

    when
        Statistic( hypoglycemiaCount == 0 )
    then
        Conclusion c = new Conclusion();
        c.setTitle("hypoglycemiaCount == 0");
        // insert(c);
        modify($s) {
            addConclusion(c);
        }
end

rule "fbgCount + twoHpgCount <= 2, and hyperglycemiaCount > 0"
    extends "fbgCount + twoHpgCount <= 2"
    ruleflow-group "determination"
    // salience 40
    lock-on-active true

    when
        Statistic( hyperglycemiaCount > 0 )
    then
        Conclusion c = new Conclusion();
        c.setTitle("hyperglycemiaCount > 0");
        // insert(c);
        modify($s) {
            addConclusion(c);
        }
end