package cloudoc.glucose;

//fbg count
rule "fbg count"
    ruleflow-group "statistic"
    lock-on-active true

	when
	    $s : Statistic()
		Number( $count : intValue )
		    from accumulate( Record( acktype in (0, 2, 4) ), count() )
	then
	    $s.setFbgCount( $s.getFbgCount() + $count );
end

//fbg normal count
rule "fbg normal count"
    ruleflow-group "statistic"
    lock-on-active true

    when
        $s : Statistic()
		Number( $count : intValue )
		    from accumulate( Record( acktype in (0, 2, 4), level == 2 ), count() )
    then
	    $s.setFbgNormalCount( $s.getFbgNormalCount() + $count );
end

//2 hpg count
rule "2 hpg count"
    ruleflow-group "statistic"
    lock-on-active true

	when
	    $s : Statistic()
		Number( $count : intValue )
		    from accumulate( Record( acktype in (1, 3, 5) ), count() )
	then
	    $s.setTwoHpgCount( $s.getTwoHpgCount() + $count );
end

//2 hpg normal count
rule "2 hpg normal count"
    ruleflow-group "statistic"
    lock-on-active true

    when
        $s : Statistic()
		Number( $count : intValue )
		    from accumulate( Record( acktype in (1, 3, 5), level == 2 ), count() )
    then
	    $s.setTwoHpgNormalCount( $s.getTwoHpgNormalCount() + $count );
end