package cloudoc.glucose;

no-loop

//fbg count
rule "fbg count new"
    ruleflow-group "statistic_new"

	when
		$r : Record( acktype in (0, 2, 4) )
	then
        Statistic s = new Statistic();
		s.setFbgCount( 1 );
		insertLogical(s);
end

//fbg normal count
rule "fbg normal count new"
    extends "fbg count new"
    ruleflow-group "statistic_new"

    when
        Record( level == 2 )
    then
        Statistic s = new Statistic();
		s.setFbgNormalCount( 1 );
		insertLogical(s);
end

//2 hpg count
rule "2 hpg count new"
    ruleflow-group "statistic_new"

	when
		$r : Record( acktype in (1, 3, 5) )
	then
        Statistic s = new Statistic();
		s.setTwoHpgCount( 1 );
		insertLogical(s);
end

//2 hpg normal count
rule "2 hpg normal count new"
    extends "2 hpg count new"
    ruleflow-group "statistic_new"

    when
        Record( level == 2 )
    then
        Statistic s = new Statistic();
		s.setTwoHpgNormalCount( 1 );
		insertLogical(s);
end
