package cloudoc.glucose;

no-loop

//fbg count
rule "fbg count"
    ruleflow-group "statistic"
    // dialect "mvel"
    // no-loop

	when
	    $s : Statistic()
		$r : Record( acktype in (0, 2, 4) )
	then
// 		modify($s) {
		    $s.setFbgCount( $s.getFbgCount() + 1 );
		    update($s);
// 		}
end

//fbg normal count
rule "fbg normal count"
    extends "fbg count"
    ruleflow-group "statistic"
    // dialect "mvel"
    // no-loop
    
    when
        Record( level == 2 )
    then
// 		modify($s) {
		    $s.setFbgNormalCount( $s.getFbgNormalCount() + 1 );
		    update($s);
// 		}
end

//2 hpg count
rule "2 hpg count"
    ruleflow-group "statistic"
    // dialect "mvel"
    // no-loop
    
	when
	    $s : Statistic()
		$r : Record( acktype in (1, 3, 5) )
	then
// 		modify($s) {
		    $s.setTwoHpgCount( $s.getTwoHpgCount() + 1 );
		    update($s);
// 		}
end

//2 hpg normal count
rule "2 hpg normal count"
    extends "2 hpg count"
    ruleflow-group "statistic"
    // dialect "mvel"
    // no-loop
    
    when
        Record( level == 2 )
    then
// 		modify($s) {
		    $s.setTwoHpgNormalCount( $s.getTwoHpgNormalCount() + 1 );
		    update($s);
// 		}
end